### ISSUE TITLE
How to flush stock firmware

### ISSUE THREAD

**Issue by dazii-dev** [msdos03/openwrt-f660#2]
How do I correctly flush the stock firmware? Tried using tftp using my pc as server then naming *.bin files as upgrade.bin one by one. But there was no change. Also tried in webui but integrity check failed.

My gpon modem version is V6.

**Comment by msdos03** [comment]
This project is for F660 V3.0 which has an 88f6560 processor, not for V6. I'm sorry, I haven't flashed any stock firmware yet. Flash firmware for F660 V6 in webUI is a good idea.

**Comment by dazii-dev** [comment]
Ok thanks
