### ISSUE TITLE
刷入到F460后wifi不稳定，速率只有10M

### ISSUE THREAD

**Issue by xiaole51** [msdos03/openwrt-f660#5]
### Describe the bug

无线设置后信号基本打不开，偶尔能打开信号时测速只有大概10M速度。
PS：
Releases 下的固件是原厂备份固件吧？ 我的有坏块没有备份完整，用整个可以恢复回去吧？
恢复远程固件还需要重刷原厂的bootloader吗？

### OpenWrt version

OpenWrt SNAPSHOT r17900+3-e06aaba4e3 / LuCI Master git-21.301.66258-0740023

### OpenWrt target/subtarget

nell

### Device

nell

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by msdos03** [comment]
追加：我发现你似乎没有在用最新的版本，用我的仓库最新代码编译再试试，也许你用的版本不包含我所说的wifi修复补丁

有更详细的信息吗？
首先，这个光猫的无线网卡在主线linux驱动的支持很差，我这里在跟前测速下载32mbps，上传35mbps
远远达不到144/300mbps的理论速度。并且信号强度很弱，指望穿墙是不可能的。
请排除一下受硬件性能限制的情况。

还有一个相关的已知问题是：软重启后有时会导致无线网卡异常

如果确认是bug，那么把故障描述得具体一点，比如在luci里看是什么状态，什么时候会发生，
ping路由器会发生什么，当出现故障时无线指示灯是否亮着等等
另外，我希望你能提供开启无线使用一段时间后的内核日志。

曾经我遇到过wifi的bug是能连上，但是不能传输任何数据。这个bug已经被修复。

但是以防万一还有我没考虑到的地方，我希望你在编译openwrt时开启“Kernel modules > Wireless Drivers >Realtek wireless debugging"选项
然后在openwrt启动后重新以debug模式加载rtl8192ce.ko模块，即：
```
rmmod rtl8192ce
insmod rtl8192ce debug_level=18 debug_mask=0x0
```
然后再把内核日志输出的东西发上来让我看一眼

> Releases 下的固件是原厂备份固件吧？ 我的有坏块没有备份完整，用整个可以恢复回去吧？

理论上只要文件没坏就可以

> 恢复远程固件还需要重刷原厂的bootloader吗？

这个压缩包里的完整固件包含uboot，刷完会把uboot恢复原厂
值得一提的是，openwrt把uboot分区设为只读，你需要在uboot里写入这个固件。

**Comment by xiaole51** [comment]
多谢老大亲自回复。

原来的固件是在恩山下载的比较老。
用最新源码编译后刷入后无线可正常开启。
测试期间遇到有无法开启现象，不过找不到规律就暂且是我操作错误吧。
![image](https://user-images.githubusercontent.com/22991235/231754025-c1e1a389-169a-4548-a5bc-24afda385a2f.png)



最新版的固件无线速度明显提升，基本接近100m速率。
如下是测速结果，带R为路由到电脑的下行速度。
![image](https://user-images.githubusercontent.com/22991235/231751195-3e7cba70-ec54-4475-86fb-d9158a276f2f.png)


还有两个问题需请教：
1. 刷回官方固件进入uboot后如何操作？ 以我理解是不是如下操作？
nand erase 0x0
tftp mtdblock0.bin
nand write 0x2000000 0x0 0xxxxxxx
这样操作后如果失败，哪就成砖了吧？

2. 编译openwrt时如何添加交换机页面， 即switch页面， 今天搜了很久没找到答案。 

建议：
1. 本库为专用设备固件，默认配置文件可固定成F660配置。 并选中最小配置。
第一次编译时还不了解硬件平台名称网上搜了好久，只选择平台编译出的固件连luci都不带。 
2. github的README.md中能带上简单的编译帮助就更好了。


最后感谢大佬的无私分享。

**Comment by msdos03** [comment]
@xiaole51 

> 原来的固件是在恩山下载的比较老。

在恩山发布帖子的时候已经很早了，那时这个项目还不成熟，那时候uboot也是一样，有几个未修复bug。
如果你的uboot不是最新版，最好更新到最新版本。

> 用最新源码编译后刷入后无线可正常开启。
测试期间遇到有无法开启现象，不过找不到规律就暂且是我操作错误吧。

你可以按无线开关按钮观察指示灯来判断一些无线的问题，我使用没有出现过这种情况
如果重启才能解决有可能是上面提到的软重启导致的无线问题，这个问题我就无能为力了。

> 刷回官方固件进入uboot后如何操作？ 以我理解是不是如下操作？

你的理解是对的；即使失败了也只有少数情况会变砖，并且可通过UART轻松救回来，这就是marvell SoC的优点了。

> 编译openwrt时如何添加交换机页面， 即switch页面， 今天搜了很久没找到答案。

你说的switch界面只有老版本openwrt使用的swconfig驱动会使用，而swconfig已经是过时的东西，不再被维护。
不久之前我成功在88f6560内置交换机上使用DSA驱动后，这个项目就抛弃了旧的swconfig驱动，转而使用DSA驱动了。
参考: [https://openwrt.org/docs/guide-user/network/dsa/converting-to-dsa](https://openwrt.org/docs/guide-user/network/dsa/converting-to-dsa)
至于DSA驱动如何配置，搜索引擎可以给你答案。

> 本库为专用设备固件，默认配置文件可固定成F660配置。 并选中最小配置。
第一次编译时还不了解硬件平台名称网上搜了好久，只选择平台编译出的固件连luci都不带。
github的README.md中能带上简单的编译帮助就更好了。

为了方便merge官方仓库，README文件保持和openwrt官方一致，
并且除了添加F660的硬件平台avanta和一个额外的wifi修复补丁 (已提交到linux内核上游，
等待新的无线驱动版本被openwrt采用) 之外没有任何改动。
为了保持和openwrt其他target一致，我没有在默认包里加luci，但是所有设备的驱动还有wpad都包含在默认包里了，
选中target即选中这些包。这其实就是最小配置。
我也考虑过方便其他人使用的方法，我可以在简介里说明我添加的platform和target名称，方便其他人编译。
