### ISSUE TITLE
E.PON/G.PON + VoIP Support

### ISSUE THREAD

**Issue by moriel5** [msdos03/openwrt-f660#6]
Hello, I just found your work while searching for Marvell's reference SFP and Ethernet Gateway ONTs.

On the OpenWrt forum (currently I cannot log in and ask there, as I am on mobile) you wrote that E.PON/G.PON and VoIP are impossible to get working, is there a reason for that?

**Comment by msdos03** [comment]
There is no PON or SLIC support in mainline linux. There is no usable driver by manufactures. 
But that's only for mainline linux, if you don't care linux version 2.6 or earlier, official SDK can do this.

**Comment by moriel5** [comment]
Thank you very much, it is certainly very concerning that the xPON situation is equal to the DOCSIS situation regarding OSS.
