### ISSUE TITLE
ZTE F660输入openwrt后一直重启

### ISSUE THREAD

**Issue by hxlnyy** [msdos03/openwrt-f660#7]
### Describe the bug

刷入您uboot-f660项目中的bin文件会出现错误
BootROM: Bad header at offset error
后面从您uboot-f660中的issues中下载了您的新bin文件后可以正确启动uboot，然后刷入openwrt会导致F660一直重启，从TTL中读取到的信息是内核崩溃，可能是我的f660中nand闪存跟您的不一样，也可能是我重新编译的固件有问题。
以下是我的固件和报错日志
[ZTE_F660.zip](https://github.com/msdos03/openwrt-avanta/files/12532812/ZTE_F660.zip)
[logs.txt](https://github.com/msdos03/openwrt-avanta/files/12532829/logs.txt)

### OpenWrt version

null

### OpenWrt target/subtarget

null

### Device

ZTE F660 V3.0

### Image kind

Official downloaded image

### Terms

- [ ] #8

**Comment by msdos03** [comment]
> 可能是我的f660中nand闪存跟您的不一样

你猜对了，那个issue里的uboot是可以适配你的nand的，但是openwrt不能。我不打算添加很多target来适配所有nand型号。你可以自己修改配置。

这个回帖里的修改方法也适合你的机器。
https://forum.openwrt.org/t/openwrt-now-support-zte-f660-v3-0-and-hgg420n/101136/18?u=winnt5

**Comment by hxlnyy** [comment]
非常感谢您的回复。已经成功编译出固件，我想请教一下，ssr plus能否编译进F660的openwrt固件里呢？

**Comment by msdos03** [comment]
@hxlnyy 自己加相应feeds就行

**Comment by hxlnyy** [comment]
谢谢大佬的回复，昨天我已经把对应的编译进去了。非常感谢您
